[package]
name = "will/militarygame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@^2.4"
Trove = "sleitnick/trove@^0.5"
Promise = "evaera/promise@^4.0.0"
Signal = "sleitnick/signal@^1.5"
Option = "sleitnick/option@^1.0"
Symbol = "sleitnick/symbol@^2.0"
Net = "sleitnick/net@^0.1"
EnumList = "sleitnick/enum-list@2.0.1"
Shake = "sleitnick/shake@0.1.7"

